project:
  status:
    not_started: 0
    in_progress: 1
    pending: 2
    completed: 3
    on_hold: 4

  classes:
    not_started: 'secondary'
    in_progress: 'primary'
    pending: 'warning'
    complited: 'success'
    on_hold: 'dark'

resource_types:
  pm: 0
  rails: 1
  qa: 2
  magento: 3
  sap: 4
  ba: 5
  front: 6
  devops: 7
  other: 8

currencies:
  usd: 0
  eur: 1
  rub: 2
  cad: 3

date_format:
  - '%m/%d/%Y'
  - '%d.%m.%Y'

assigned_resource:
  forecast:
    types:
      distribution: 0
      allocation: 1
    classes:
      distribution: 0
      allocation: 1

assumptions:
  working_hours: 8
  estimate_buffer: 20%
  code_complete_prior: 10
